### ISSUE TITLE
When should I use this lib instead of `TVFocusGuideView` provided by react-native-tvos

### ISSUE THREAD

**Issue by evoactivity** [bamlab/react-tv-space-navigation#124]
It seems they both solve the same problem. What benefits does this library offer over `TVFocusGuideView`?

**Comment by pierpo** [comment]
Hey!

The main benefit is cross-platform compatibility and predictability.
The lib allows to have a behaviour that is 100% identical across tvOS / AndroidTV / web TVs.

If you're not interested in web compatibility, I would say that you might be better off with the native focus system that is becoming better and better 😊 
There are still issues with the native system that you wouldn't get with this library, but this library has other trade-offs (most notably the accessibility support and some implementation tricks that are not super obvious - even though you can see them in our example).

Cheers 👋
