### ISSUE TITLE
Unable to Install "Expo Go" This app is not made for this device.

### ISSUE THREAD

**Issue by vogdev** [bamlab/react-tv-space-navigation#134]
**Describe the bug**
i just installed Apple TV 4K (2nd generation) (at 1080p) Simulator to test the APP

**To Reproduce**
```tsx
Xcode Version 15.0 (15A240d)
```

**Expected behavior**
i run yarn install

**Screenshots**
![Screenshot 2024-06-04 at 15 32 22](https://github.com/bamlab/react-tv-space-navigation/assets/20149487/ac67df85-fb21-4e4d-8721-ff253636244a)

**Version and OS**
 - Library version: "react-native": "npm:react-native-tvos@0.74.1-0"
 - OS Apple M1 Pro

**Comment by vogdev** [comment]
thank u @pierpo it works fine now 
1 => git checkout d0a53b8c6a643f3d45f86c61ccdcd3af8954797e
2 => rm .xcode.env.local
3 => yarn ios

**Comment by pierpo** [comment]
Cool, but does it still work on `main`? :joy:

**Comment by vogdev** [comment]
I checked on the main branch, and everything is working fine there as well thank you.

<img width="1515" alt="Screenshot 2024-06-04 at 23 56 20" src="https://github.com/bamlab/react-tv-space-navigation/assets/20149487/f7f5b9de-d8dc-4850-83d5-74de87892ff7">
