### ISSUE TITLE
Modal focus losing

### ISSUE THREAD

**Issue by yusufusta** [bamlab/react-tv-space-navigation#137]
**Describe the bug**
The focus of the buttons in the modal disappears after a few seconds and the focus is on the first element.

**To Reproduce**
Same code as example

**Screenshots**

https://github.com/bamlab/react-tv-space-navigation/assets/46392667/4288235d-0d0d-4a2a-a936-49e93c976882

**Version and OS**

 - Library version: 3.6.0
 - React Native version: 0.71.10
 - OS: Web

**Comment by yusufusta** [comment]
This is what happens when the state changes behind the modal while it is open. I fixed this but I think there is a problem.

**Comment by pierpo** [comment]
Hey! Thank you for the video. I didn't really understand the problem though 😂 
What did you do during the video? You have your focus, you go right-right... then the focus is lost and comes back to first element?

Can you share a piece of code, and how you solved it?

Thanks!

**Comment by yusufusta** [comment]
Yes, you are right @pierpo 😅.

Let me explain: A modal opens, and I move the focus to another element by going to the right. However, when states change in the background, the focus returns to the default focus. In other words, the focus goes back to the beginning.
