### ISSUE TITLE
SpatialNavigationVirtualizedList boundaries

### ISSUE THREAD

**Issue by Veryyapeee** [bamlab/react-tv-space-navigation#143]
**Describe the bug**
Currently due to the fact that SpatialNavigationVirtualizedList is using translate, I can't really add any boundaries

I'd like my list to be for example width of 500, and I don't want the scrolled elements to go beyond that width, simply adding styles is not enough

Also playing around with overflow: 'hidden' is not causing the perfect result .

**To Reproduce**
```tsx
<SpatialNavigationVirtualizedList style={{width: 500}} />
```

**Expected behavior**

**Screenshots**

**Version and OS**
 - Library version: [e.g. 1.0.0]
 - React Native version: [e.g. 0.71.2]
 - OS [e.g. Android, web]

**Additional context**

**Comment by pierpo** [comment]
Hey! I think I managed to do that already. Have you tried putting the virtualized list inside a parent view that has width 500?

I realize that something is not very clear: the virtualized list will compute the parent's width and hardcore its width. You can't change its width by setting the style 😊

**Comment by Veryyapeee** [comment]
> Hey! I think I managed to do that already. Have you tried putting the virtualized list inside a parent view that has width 500?
> 
> I realize that something is not very clear: the virtualized list will compute the parent's width and force its width. You can't change its width by setting the style 😊

Yup, I've tried, and seems like it's not working, the only thing that was working was adding the overflow: hidden to the parent element, but this was kinda tricky, and wasn't working in every case, and was breaking the UI in some cases

**Comment by pierpo** [comment]
Hey @Veryyapeee, I need more details to help with this 😁  I'm closing, but feel free to reopen with additional info!
