### ISSUE TITLE
Lag and choppiness when doing press-and-hold fast scroll with remote

### ISSUE THREAD

**Issue by ksvslk** [bamlab/react-tv-space-navigation#168]
**Describe the bug**
Lag and choppiness when holding down the remote left/right button to scroll horizontally.

**To Reproduce**
Run the example (hoppix) on Android TV. I made a release build.

**Expected behavior**
Smooth scroll without lag or choppiness.

**Screenshots**
Believe me, it is laggy.

**Version and OS**
 - 5.1.0
 - react-native-tvos@0.74.1-0
 - Google Chromecast

**Additional context**
I believe the creators have not focused on this problem and it is expected?

**Comment by pierpo** [comment]
Hey, are you trying in release mode? It can be sloppy in debug mode (React Native is quite slow in debug mode), but shouldn't be in release mode.

Having a good performance is important for us, and we did check on low-end devices (Xiaomi TV Box). I'm quite surprised that it's slow for you 🤔

**Comment by pierpo** [comment]
Hey, someone else was talking about the app and told me that there was a big slowness that was weird, and noticed that reanimated was causing issues 😱 

Removing this part greatly improves the smoothness of the app (even though the animation isn't even used if you don't use a longPress)

https://github.com/bamlab/react-tv-space-navigation/blob/3c53f44f0b91e06146df0b7c3a9d46f945d8a86b/packages/example/src/modules/program/view/ProgramNode.tsx#L35

We will fix this in the example soon by removing reanimated, probably 😬

**Comment by ksvslk** [comment]
> Hey, someone else was talking about the app and told me that there was a big slowness that was weird, and noticed that reanimated was causing issues 😱
> 
> Removing this part greatly improves the smoothness of the app (even though the animation isn't even used if you don't use a longPress)
> 
> https://github.com/bamlab/react-tv-space-navigation/blob/3c53f44f0b91e06146df0b7c3a9d46f945d8a86b/packages/example/src/modules/program/view/ProgramNode.tsx#L35
> 
> We will fix this in the example soon by removing reanimated, probably 😬

Hi! Thank you for pointing this out. I think the best way to deal with this is to remove the animation as this does not contribute to the experience so much !

**Comment by pierpo** [comment]
Indeed, in this case it was just an example 😄 So you confirm that it improves smoothness a lot?

**Comment by ksvslk** [comment]
> Indeed, in this case it was just an example 😄 So you confirm that it improves smoothness a lot?

Seems pretty smooth to me on Tizen 5.5 for example 🤩

**Comment by pierpo** [comment]
That's awesome. Thank you for pointing this out 😁
