### ISSUE TITLE
Handling long press events

### ISSUE THREAD

**Issue by pierpo** [bamlab/react-tv-space-navigation#36]
**Is your feature request related to a problem? Please describe.**
We can't detect a long press right now.

**Describe the solution you'd like**

```
<SpatialNavigationNode isFocusable onLongSelect={() => {}} />
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fulminant** [comment]
+1. It would be a great feature.

**Comment by fulminant** [comment]
Investigated this issue a little bit, and I can say that it is not an easy task.
LRUD library doesn't handle long press events in any variant.
That means that to implement this feature we need to modify LRUD library and add `longPress` handle there and only after that implement it in SpatialNode.

We can use `react-native` `Pressable` component for example and see how it is accomplished there.
https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Pressability/Pressability.js
There are a lot of tricky moments in this code.

**Comment by pierpo** [comment]
Added since v5.0.0 😊
