### ISSUE TITLE
Support for mouse pointer

### ISSUE THREAD

**Issue by pierpo** [bamlab/react-tv-space-navigation#41]
**Is your feature request related to a problem? Please describe.**
Some TVs have a pointer. We should be able to support it.

**Describe the solution you'd like**
We can use the mouse enter/exit events and trigger focus events in the lib.
The tricky part is the scrolling on the list that should not happen in the same way when using a pointer.

**Comment by pierpo** [comment]
We've been working on it a little bit.
There are some results, but this still needs improvement :)

https://github.com/bamlab/react-tv-space-navigation/pull/63

**Comment by adheus** [comment]
That's a nice request! It's a requirement for the LG webOS!
Thank you, @pierpo!

**Comment by pierpo** [comment]
Released in v2.0.0 🎉 
Check out the README for the instructions to make it work :)

You may check out the example app as well!
