### ISSUE TITLE
onSelect is getting called multiple times when i use the same component in multiple pages

### ISSUE THREAD

**Issue by manjunath-nuveb** [bamlab/react-tv-space-navigation#43]
**Describe the bug**
When the same component is used on multiple pages onSelect is called multiple times

**To Reproduce**
home.tsx 
```
<Container width={width} height={height}>
      <Page>
        <DefaultFocus>
          <SpatialNavigationScrollView offsetFromStart={140}>
            <Box padding="$10">
              <HeroWrapper data={data} />
              <Spacer gap="$20" />
              <SwiperListWrapper data={data} title="Latest in *" />
              <Spacer gap="$20" />
            </Box>
          </SpatialNavigationScrollView>
        </DefaultFocus>
      </Page>
      <Menu />
    </Container>
```

singleOttPage.tsx

```
<Container width={width} height={height}>
      <Page>
        <SpatialNavigationScrollView offsetFromStart={140}>
          <Box padding="$10">
            <View>
              <Hero
                key={mainVideo.title}
                fullData={mainVideo.fullData}
                image={mainVideo.image}
                width={avilableWidth}
                height={aspectRatioHeight}
                title={mainVideo.title}
                descArray={mainVideo.descArray}
                rating={mainVideo.rating}
                desc={mainVideo.fullData?.standaloneTitleDetails?.logLine}
                onSelect={(onSelect) => {}}
                buttons={buttons}
              />
            </View>
            <Spacer gap="$10" />
           </Box>
        </SpatialNavigationScrollView>
      </Page>
      <Menu />
    </Container>
```

The menu component is same as the one in example folder. 
I have 2 pages. Home page and single video page. when click on the menu item I'm pushing the route, ```navigation.push(route)``` 
First-time menu click works as expected but after navigation, onSelect is called multiple times and I also get the warning 
`[React Spatial Navigation] No registered node on this page.`
Same behaviour is happening on hero card and swiper card too.

**Expectedbehaviourr**
onSelect should be called only once

**Comment by pierpo** [comment]
Hey!

Are you using react-navigation?
Are you sure you are disabling the `SpatialNavigator` on the pages that don't have the focus ? 😄 
Because they still live in the background and still listen for keyboard events.

References in the example : 
- https://github.com/bamlab/react-tv-space-navigation/blob/a5fd1e0cac04e0808ab79e1ea95ccf91106913e5/packages/example/src/components/Page.tsx#L38
- https://github.com/bamlab/react-tv-space-navigation/blob/a5fd1e0cac04e0808ab79e1ea95ccf91106913e5/packages/example/src/components/Page.tsx#L51

**Comment by manjunath-nuveb** [comment]
It is present in Page.tsx. however, in the example menu was rendered only once in APP.tsx. I have moved it to each page 
I will add it there too.

**Comment by pierpo** [comment]
Yes the menu is rendered once for everywhere to be able to keep its state. It has caused us animation issues to have one menu rendered per page. But it's a valid choice to have one menu per page 👍 

I don't understand your problem though 🤔 
Having multiple `onSelect` really means that you have multiple active instances of the spatial navigator. There's no other way to have multiple `onSelect` triggered at once.

Can you make sure that you have only ONE spatial navigator active at the same time?
