### ISSUE TITLE
SpatialNavigationVirtualizedGrid : Focused item is not in viewport

### ISSUE THREAD

**Issue by manjunath-nuveb** [bamlab/react-tv-space-navigation#45]
**Describe the bug**
Using SpatialNavigationVirtualizedGrid to render grid. The focused item is not visible in the viewport.  

**To Reproduce**
```
<SpatialNavigationVirtualizedGrid
          itemHeight={200}
          numberOfColumns={3}
          data={[
            {
              index: 0,
            },
            {
              index: 1,
            },
            {
              index: 2,
            },
            {
              index: 3,
            },
            {
              index: 4,
            },
            {
              index: 5,
            },
            {
              index: 6,
            },
            {
              index: 7,
            },
            {
              index: 8,
            },
            {
              index: 9,
            },
            {
              index: 10,
            },
            {
              index: 11,
            },
          ]}
          renderItem={({ item }) => (
            <SpatialNavigationNode isFocusable>
              {({ isFocused }) => (
                <View
                  className={`w-[200] h-[180] bg-theme-100 border ${
                    isFocused ? 'border-white' : ''
                  }`}
                />
              )}
            </SpatialNavigationNode>
          )}
          numberOfRenderedRows={3 + 2}
          numberOfRowsVisibleOnScreen={3}
          onEndReachedThresholdRowsNumber={3 - 1}
          rowContainerStyle={{
            gap: 20,
            paddingVertical: 20,
          }}
        />
```

**Expected behavior**
Last row should be in viewport when focused

**Screenshots**

https://github.com/bamlab/react-tv-space-navigation/assets/138149089/c92d5f5c-b150-4a4c-acf7-eafd7802b92a

**Comment by pierpo** [comment]
Hey!

Maybe it lacks of clarity, but I think you should have "numberOfRowsVisibleOnScreen={2}". Have you tried it? :)
It should mention that "numberOfRowsFULLYVisibleOnScreen" 😁

**Comment by manjunath-nuveb** [comment]
thanks @pierpo .

**Comment by manjunath-nuveb** [comment]
<img width="1077" alt="Screenshot 2023-12-22 at 10 45 24 PM" src="https://github.com/bamlab/react-tv-space-navigation/assets/138149089/c10759e0-16ba-41bf-8cfb-0dff107f61c4">
@pierpo 
on scale-up animation, the card is not visible completely. it considers the original top position/ height of the card. 
how to fix it

**Comment by pierpo** [comment]
Shouldn't you add a little padding on top?
The grid does not provide any.

This requires additional documentation for sure :)

**Comment by ionictest2017** [comment]
> <img alt="Screenshot 2023-12-22 at 10 45 24 PM" width="1077" src="https://private-user-images.githubusercontent.com/138149089/292552692-c10759e0-16ba-41bf-8cfb-0dff107f61c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODA1MDYsIm5iZiI6MTcwNTU4MDIwNiwicGF0aCI6Ii8xMzgxNDkwODkvMjkyNTUyNjkyLWMxMDc1OWUwLTE2YmEtNDFiZi04Y2ZiLTBkZmYxMDdmNjFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMjE2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjE4NTY5NjMxNDIxYjkyNTBkZTlhNzBiOWVmNmZjM2ExNjAxYjhhNDJhMTIxNWVjOWFjNzBiMjY3YzRlZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I4_rDCJasHw5e2EyEf4INV8WUno_QgXeA4efJ8NFQgU"> @pierpo on scale-up animation, the card is not visible completely. it considers the original top position/ height of the card. how to fix it

@manjunath-nuveb can you help me with a simple example of menu for Android TV app react native cli

**Comment by pierpo** [comment]
@manjunath-nuveb any news? I don't understand the exact problem, it really feels like this is a missing padding 😁

**Comment by manjunath-nuveb** [comment]
@pierpo  Sorry for the late reply, 
I have tried applying padding to SpatialNavigationVirtualizedGrid. It is still overflowing viewport on scaleUp

**Comment by pierpo** [comment]
Closing this as we are lacking details to answer!
