### ISSUE TITLE
How to hide menu for some screen

### ISSUE THREAD

**Issue by ionictest2017** [bamlab/react-tv-space-navigation#48]
please let me know how to hide side menu for some screen, I am unable to do this

**Comment by pierpo** [comment]
Good point. I wanted to implement this but never took the time, sorry. I wanted to implement the menu router as well.

What you need to do is have different react navigation stacks. At the root of your navigation, I think you should have a stack with a menu and a stack without a menu 🤔

**Comment by ionictest2017** [comment]
**This is the my navigation component**
  <Stack.Navigator
        initialRouteName="Home"
        screenOptions={{
          headerTitle: false,
          headerTransparent: true,
          headerBackTitleVisible: false,
          headerShown: false,
        }}
        >
        <Stack.Screen
          name="Home"
          component={HomeDrawerNavigator}
          options={{headerShown: false}}
        />
        <Stack.Screen name="MovieDetail" component={MovieDetailScreenNew} />
        <Stack.Screen name="Player" component={Player} />
        <Stack.Screen name="MovieCastDetail" component={MovieCastDetail} />
      </Stack.Navigator>

**and this is my main app.tsx file.**

<Provider store={store}>
    <NavigationContainer linking={linking}>
      <ThemeProvider theme={theme}>
        <GoBackConfiguration />
        <MenuProvider>
          <Container width={width} height={height}>
            <Navigation/>
            <Menu />
          </Container>
        </MenuProvider>
      </ThemeProvider>
    </NavigationContainer>
    </Provider>

**Can you tell me how to hide the Menu from the Player screen? I am a little bit confused please Help me**

**Comment by pierpo** [comment]
We'll probably implement this in the coming days.

I was wrong above, you need a nested Tabs stack with a menu.
I'm quite rusty with react navigation so I forgot, but the idea is to have

```
Root
  TabsStack (containing the menu)
    PageWithMenuA
    PageWithMenuB
  Stack
    PageWithoutMenuA
    PageWithoutMenuB
```

Can't give you the details of the code yet, sorry!

**Comment by pierpo** [comment]
Just merged your use case in the example app 😉 
You can check it out!
