### ISSUE TITLE
Unable to get focus on Modal popup

### ISSUE THREAD

**Issue by ionictest2017** [bamlab/react-tv-space-navigation#54]
while default or native focus is working in modal

**Modal should be inside a screen**

**Please Help me**

**Comment by pierpo** [comment]
Hey, can you detail what kind of modal you're working with?

If you're working with a native modal, you can lock our custom spatial navigation while the modal is open by using `useLockSpatialNavigation` https://github.com/bamlab/react-tv-space-navigation/blob/main/docs/api.md#uselockspatialnavigation

**Comment by ionictest2017** [comment]
I need to show the modal for Player setting button like subtitle, multi-audio, resolution, etc.

I also want to ask one thing, why after using this library touchable opacity onPress event is not working?

**Comment by ionictest2017** [comment]
actually, i am developing app for all platforms like TV, web, and mobile

**Comment by pierpo** [comment]
Well, having a gradient is not this lib's responsibility so I can help but this would be totally unrelated 😄 
Feel free to share some code if you wan't some ideas.

I'm closing this issue and open a feature request in a different one for the sake of clarity.

**Comment by ionictest2017** [comment]
> > I need to show the modal for Player setting button like subtitle, multi-audio, resolution, etc.
> 
> It's something in the backlog, we have no clear recommendation on how to do a modal for now. It's totally possible but we should show an example.
> 
> For now, you can probably use
> 
> ```tsx
> <SpatialNavigationRoot isActive={isModalOpen ? false : true}>
>   {/* ... your layout */}
>   <View />
> 
>   {/* you can nest another spatial navigation root when your modal is open, it should work but I haven't tried */}
>   {isModalOpen && (
>     <SpatialNavigationRoot>
>       {/* your modal layout... */}
>     </SpatialNavigationRoot>
>   )}
> </SpatialNavigationRoot>
> ```
> 
> > I also want to ask one thing, why after using this library touchable opacity onPress event is not working?
> > Maybe we should clarify this in the README.
> 
> This library totally bypasses the native focus. The whole point is to have our own focus system made purely in React (no React Native involved in the core of the lib) so that we don't rely on anything native. The whole point is to have the **exact** same behaviour on web, tvOS and AndroidTV.
> 
> So, we don't use TouchableOpacity, and using some will mess up with the lib as you will mix up native focus and custom focus 😉

I have used your suggestions but focus still present on parent screen

**Comment by pierpo** [comment]
We have a complete modal example coming up 😉 
It's still WIP but it's working.

You can check it out and compare with your code:
https://github.com/bamlab/react-tv-space-navigation/pull/59

**Comment by ionictest2017** [comment]
@pierpo can you let me know how to use it **(const { lock, unlock } = useLockSpatialNavigation();)** in class base component in react native
