### ISSUE TITLE
Hide a side menu in a specific page

### ISSUE THREAD

**Issue by jcgomeze** [bamlab/react-tv-space-navigation#60]
Hi,

According to the documentation, it says, "Handling a side menu
You can check out the example app for this.

Usually, when we integrate a side menu in a TV app, it should persist across pages. It is an element on the border of the screen that overlays the root view."

However, I need to hide a side menu on a specific page. How can I do that?

**Comment by manjunath-nuveb** [comment]
I moved the menu from the root of the project to an individual page

**Comment by pierpo** [comment]
Yes exactly. Make your page a menu-less page, and add a custom menu in your page specifically.
This should work without any issue :)
